### ISSUE TITLE
Running `pytest .` after cloning fails with RuntimeError: Preprocessing not completed in 10 seconds

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples#112]
![image](https://github.com/IDAES/examples/assets/48035537/a046f2d9-9348-465e-b3e8-a55aa7ca13e7)

## Steps to reproduce

```sh
git clone https://github.com/IDAES/examples && cd examples
conda create --name test-idaes-examples python=3.10 && conda activate test-idaes-examples
pip install -r requirements-dev.txt
pytest .
```

## Known workarounds

If instead `pytest idaes_examples` is run first, even partially, `pytest .` will work as it should:

![image](https://github.com/IDAES/examples/assets/48035537/4a45d20a-779e-4d58-8340-4a7e6c4a0a01)

**Comment by dangunter** [comment]
There was some logic changed in conftest.py that should fix this. Somewhat confusingly it was added in PR #129

**Comment by ksbeattie** [comment]
I just tried to reproduce this, and I could (on my MacOS M3 laptop).

Running `pytest .` initially failed with `RuntimeError: Preprocessing not completed in 10 seconds.`. After running `pytest idaes_examples` (which also failed because I didn't bother to install ipopt) running `pytest .` finished (with failures about ipopt not being present).
