### ISSUE TITLE
potential tutorial error - "Cubic root external functions are not available."

### ISSUE THREAD

**Issue by ian-moskowitz** [IDAES/examples#123]
Hello,

I'm trying to work with the Peng-Robinson equation of state and am getting a RuntimeError "Cubic root external functions are not available."

I went into the documentation to try and sort through it, and appears this [error is in the documentation as well.](https://idaes-examples.readthedocs.io/en/stable/docs/properties/parameter_estimation_pr_doc.html#solving-square-problem)

I believe the issue causing this error raised in the documentation is the same that raises it for my local problem - thus I'll lean on the documentation example rather than walking through my setup.

Thanks for any support!

Best,
Ian

**Comment by lbianchi-lbl** [comment]
Hi @ian-moskowitz, thanks for opening this issue.

- The error messages being displayed in the HTML documentation hosted by ReadTheDocs have been addressed recently in #122, and the updated version is already available on ReadTheDocs at https://idaes-examples.readthedocs.io/en/latest
- To resolve the "Cubic root external functions are not available", you can try to run the command `idaes get-extension`. You can run this in a terminal, after activating the environment where IDAES is installed. For more information about the IDAES extension, you can refer to the IDAES "Getting Started" tutorial specific to your operating system: https://idaes-pse.readthedocs.io/en/stable/tutorials/getting_started/index.html#os-specific-instructions
- Since this last step is not clearly mentioned in the installation instructions for the IDAES examples, I've opened FIXME issue as a way to remind us to improve the documentation so that future users don't run in the same situation

**Comment by ian-moskowitz** [comment]
ah - thanks for the quick response!  That did it! 

just for documentation for a future person checking this out, I ran `idaes get-extensions` (an 's' at the end of the command, was possibly a typo or perhaps a different version).

**Comment by lbianchi-lbl** [comment]
> ah - thanks for the quick response! That did it!
> 
> just for documentation for a future person checking this out, I ran `idaes get-extensions` (an 's' at the end of the command, was possibly a typo or perhaps a different version).

Thanks a lot for catching that, it was indeed a typo and the correct command is `idaes get-extensions` (I've edited my original post).
